# Generated by Django 6.0.1 on 2026-01-21 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOADED', 'Документ загружен'), ('VIEWED', 'Документ просмотрен'), ('UPDATED', 'Документ обновлен'), ('DELETED', 'Документ удален'), ('DOWNLOADED', 'Документ скачан')], max_length=20, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dms.document', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_activities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие с документом',
                'verbose_name_plural': 'Действия с документами',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dms_documen_user_id_d211e1_idx'), models.Index(fields=['document', '-created_at'], name='dms_documen_documen_7f3fc2_idx')],
            },
        ),
    ]
