# Generated by Django 6.0.1 on 2026-01-24 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_alter_department_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_accesses', to='dms.department', verbose_name='Отдел, которому выдан доступ')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='dms.document', verbose_name='Документ')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_document_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал доступ')),
            ],
            options={
                'verbose_name': 'Доступ к документу',
                'verbose_name_plural': 'Доступы к документам',
                'unique_together': {('document', 'department')},
            },
        ),
    ]
