# Generated by Django 6.0.1 on 2026-01-25 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_documentaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentaccess',
            options={},
        ),
        migrations.AlterField(
            model_name='documentaccess',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_accesses', to='dms.department'),
        ),
        migrations.AlterField(
            model_name='documentaccess',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='dms.document'),
        ),
        migrations.AlterField(
            model_name='documentaccess',
            name='granted_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
