# Generated by Django 6.0.2 on 2026-02-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_alter_document_department_folder_document_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
