# Generated by Django 6.0.2 on 2026-02-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_document_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
