# Generated by Django 6.0.2 on 2026-02-04 17:19

import dms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0008_document_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to=dms.models.document_upload_path, verbose_name='Файл'),
        ),
    ]
