# Generated by Django 6.0.2 on 2026-02-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_alter_document_doc_date_alter_document_doc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='document',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='dms.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_date',
            field=models.DateField(blank=True, help_text='Может быть пустой на этапе загрузки', null=True, verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, verbose_name='Извлечённый текст'),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='dms.folder', verbose_name='Папка'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['folder'], name='dms_documen_folder__b806b5_idx'),
        ),
    ]
