# Generated by Django 6.0.1 on 2026-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0018_organization_tenancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['organization__name', 'name'], 'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типы документов'},
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='dms_documen_organiz_933962_idx',
            old_name='dms_documen_organiz_78c5e0_idx',
        ),
        migrations.RenameIndex(
            model_name='documentrelation',
            new_name='dms_documen_from_do_dd0374_idx',
            old_name='dms_documen_from_do_64c9d4_idx',
        ),
        migrations.RenameIndex(
            model_name='documentrelation',
            new_name='dms_documen_to_docu_7c6267_idx',
            old_name='dms_documen_to_docu_6a8081_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmember',
            new_name='dms_organiz_user_id_a7b567_idx',
            old_name='dms_organiz_user_id_5bcd6b_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmember',
            new_name='dms_organiz_organiz_b583ef_idx',
            old_name='dms_organiz_organiz_179b71_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, verbose_name='Извлеченный текст'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('APPROVED', 'Актуальный'), ('ARCHIVED', 'В архиве')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='action',
            field=models.CharField(choices=[('UPLOADED', 'Документ загружен'), ('VIEWED', 'Документ просмотрен'), ('UPDATED', 'Документ обновлен'), ('DELETED', 'Документ удален'), ('DOWNLOADED', 'Документ скачан'), ('ARCHIVED', 'Документ переведен в архив')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('APPROVED', 'Актуальный'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='dms_documen_status_69b475_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['language'], name='dms_documen_languag_fb09fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['retention_until'], name='dms_documen_retenti_c669af_idx'),
        ),
    ]
