# Generated by Django 6.0.1 on 2026-05-11 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0021_auditevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Документ загружен'), ('DOCUMENT_UPDATED', 'Документ обновлен'), ('DOCUMENT_VIEWED', 'Документ просмотрен'), ('DOCUMENT_DOWNLOADED', 'Документ скачан'), ('DOCUMENT_VERSION_VIEWED', 'Версия документа просмотрена'), ('DOCUMENT_VERSION_DOWNLOADED', 'Версия документа скачана'), ('DOCUMENT_DELETED', 'Документ удален'), ('DOCUMENT_ACCESS_GRANTED', 'Доступ к документу выдан'), ('DOCUMENT_ACCESS_REVOKED', 'Доступ к документу отозван'), ('DOCUMENT_STATUS_CHANGED', 'Статус документа изменен'), ('AI_PROCESSING_STARTED', 'AI-обработка начата'), ('AI_PROCESSING_COMPLETED', 'AI-обработка завершена'), ('AI_PROCESSING_FAILED', 'AI-обработка завершилась ошибкой'), ('AI_FIELD_CONFIRMED', 'AI-поле подтверждено'), ('AI_FIELD_REJECTED', 'AI-поле отклонено'), ('AI_FIELDS_APPLIED', 'AI-поля применены к документу')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает обработки'), ('RUNNING', 'В обработке'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка'), ('REVIEWED', 'Проверено')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('UPLOAD', 'Загрузка документа'), ('MANUAL', 'Ручной запуск')], default='MANUAL', max_length=20, verbose_name='Источник')),
                ('parser_name', models.CharField(default='ai_parser.parse_document', max_length=100, verbose_name='Parser')),
                ('extracted_text_length', models.PositiveIntegerField(default=0, verbose_name='Длина извлеченного текста')),
                ('raw_result', models.JSONField(blank=True, default=dict, verbose_name='Raw AI result')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата старта')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processing_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='dms.document', verbose_name='Документ')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='dms.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'AI processing job',
                'verbose_name_plural': 'AI processing jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64, verbose_name='Поле')),
                ('label', models.CharField(max_length=128, verbose_name='Название поля')),
                ('value', models.TextField(blank=True, default='', verbose_name='Значение')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Уверенность')),
                ('status', models.CharField(choices=[('SUGGESTED', 'Предложено'), ('CONFIRMED', 'Подтверждено'), ('REJECTED', 'Отклонено'), ('APPLIED', 'Применено')], db_index=True, default='SUGGESTED', max_length=20, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата применения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='dms.document', verbose_name='Документ')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracted_fields', to='dms.organization', verbose_name='Организация')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extracted_fields', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dms.processingjob', verbose_name='Processing job')),
            ],
            options={
                'verbose_name': 'Extracted field',
                'verbose_name_plural': 'Extracted fields',
                'ordering': ['field_name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['organization', '-created_at'], name='dms_process_organiz_46fe5e_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['document', '-created_at'], name='dms_process_documen_c0b6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', '-created_at'], name='dms_process_status_6bd798_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedfield',
            index=models.Index(fields=['organization', 'status'], name='dms_extract_organiz_604c34_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedfield',
            index=models.Index(fields=['document', 'status'], name='dms_extract_documen_ec29f7_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedfield',
            index=models.Index(fields=['job', 'status'], name='dms_extract_job_id_b2de36_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractedfield',
            constraint=models.UniqueConstraint(fields=('job', 'field_name'), name='unique_extracted_field_per_job'),
        ),
    ]
