# Generated by Django 6.0.1 on 2026-05-11 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0022_alter_auditevent_event_type_processingjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Документ загружен'), ('DOCUMENT_UPDATED', 'Документ обновлен'), ('DOCUMENT_VIEWED', 'Документ просмотрен'), ('DOCUMENT_DOWNLOADED', 'Документ скачан'), ('DOCUMENT_VERSION_VIEWED', 'Версия документа просмотрена'), ('DOCUMENT_VERSION_DOWNLOADED', 'Версия документа скачана'), ('DOCUMENT_DELETED', 'Документ удален'), ('DOCUMENT_ACCESS_GRANTED', 'Доступ к документу выдан'), ('DOCUMENT_ACCESS_REVOKED', 'Доступ к документу отозван'), ('DOCUMENT_STATUS_CHANGED', 'Статус документа изменен'), ('AI_PROCESSING_STARTED', 'AI-обработка начата'), ('AI_PROCESSING_COMPLETED', 'AI-обработка завершена'), ('AI_PROCESSING_FAILED', 'AI-обработка завершилась ошибкой'), ('AI_FIELD_CONFIRMED', 'AI-поле подтверждено'), ('AI_FIELD_REJECTED', 'AI-поле отклонено'), ('AI_FIELDS_APPLIED', 'AI-поля применены к документу'), ('IMPORT_BATCH_CREATED', 'Партия импорта создана'), ('IMPORT_FILE_IMPORTED', 'Файл импортирован'), ('IMPORT_FILE_DUPLICATE', 'Дубликат при импорте'), ('IMPORT_FILE_FAILED', 'Ошибка импорта файла')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает импорта'), ('PROCESSING', 'В обработке'), ('COMPLETED', 'Завершено'), ('COMPLETED_WITH_ERRORS', 'Завершено с ошибками'), ('FAILED', 'Ошибка')], db_index=True, default='PENDING', max_length=30, verbose_name='Статус')),
                ('source', models.CharField(default='multiple_upload', max_length=50, verbose_name='Источник')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='Всего файлов')),
                ('imported_files', models.PositiveIntegerField(default=0, verbose_name='Импортировано')),
                ('duplicate_files', models.PositiveIntegerField(default=0, verbose_name='Дубликаты')),
                ('failed_files', models.PositiveIntegerField(default=0, verbose_name='Ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='dms.department', verbose_name='Отдел')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='dms.folder', verbose_name='Папка')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='dms.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Import batch',
                'verbose_name_plural': 'Import batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='SHA-256')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('IMPORTED', 'Импортирован'), ('DUPLICATE', 'Дубликат'), ('FAILED', 'Ошибка')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dms.importbatch', verbose_name='Партия импорта')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_files', to='dms.document', verbose_name='Созданный документ')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_import_files', to='dms.document', verbose_name='Дубликат документа')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_files', to='dms.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Import file',
                'verbose_name_plural': 'Import files',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['organization', '-created_at'], name='dms_importb_organiz_c94e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['created_by', '-created_at'], name='dms_importb_created_09b45b_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status', '-created_at'], name='dms_importb_status_2d4df0_idx'),
        ),
        migrations.AddIndex(
            model_name='importfile',
            index=models.Index(fields=['batch', 'status'], name='dms_importf_batch_i_dcc6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='importfile',
            index=models.Index(fields=['organization', 'checksum_sha256'], name='dms_importf_organiz_d80ec2_idx'),
        ),
    ]
