# Generated by Django 6.0.1 on 2026-05-11 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0023_alter_auditevent_event_type_importbatch_importfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Документ загружен'), ('DOCUMENT_UPDATED', 'Документ обновлен'), ('DOCUMENT_VIEWED', 'Документ просмотрен'), ('DOCUMENT_DOWNLOADED', 'Документ скачан'), ('DOCUMENT_VERSION_VIEWED', 'Версия документа просмотрена'), ('DOCUMENT_VERSION_DOWNLOADED', 'Версия документа скачана'), ('DOCUMENT_DELETED', 'Документ удален'), ('DOCUMENT_ACCESS_GRANTED', 'Доступ к документу выдан'), ('DOCUMENT_ACCESS_REVOKED', 'Доступ к документу отозван'), ('DOCUMENT_STATUS_CHANGED', 'Статус документа изменен'), ('AI_PROCESSING_STARTED', 'AI-обработка начата'), ('AI_PROCESSING_COMPLETED', 'AI-обработка завершена'), ('AI_PROCESSING_FAILED', 'AI-обработка завершилась ошибкой'), ('AI_FIELD_CONFIRMED', 'AI-поле подтверждено'), ('AI_FIELD_REJECTED', 'AI-поле отклонено'), ('AI_FIELDS_APPLIED', 'AI-поля применены к документу'), ('IMPORT_BATCH_CREATED', 'Партия импорта создана'), ('IMPORT_FILE_IMPORTED', 'Файл импортирован'), ('IMPORT_FILE_DUPLICATE', 'Дубликат при импорте'), ('IMPORT_FILE_FAILED', 'Ошибка импорта файла'), ('WORKFLOW_STARTED', 'Workflow started'), ('WORKFLOW_APPROVED', 'Workflow approved'), ('WORKFLOW_REJECTED', 'Workflow rejected'), ('WORKFLOW_CHANGES_REQUESTED', 'Workflow changes requested'), ('WORKFLOW_COMMENTED', 'Workflow commented'), ('WORKFLOW_COMPLETED', 'Workflow completed')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('IN_REVIEW', 'In review'), ('CHANGES_REQUESTED', 'Changes requested'), ('REJECTED', 'Rejected'), ('APPROVED', 'Актуальный'), ('ARCHIVED', 'В архиве')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='action',
            field=models.CharField(choices=[('UPLOADED', 'Документ загружен'), ('VIEWED', 'Документ просмотрен'), ('UPDATED', 'Документ обновлен'), ('DELETED', 'Документ удален'), ('DOWNLOADED', 'Документ скачан'), ('ARCHIVED', 'Документ переведен в архив'), ('WORKFLOW_STARTED', 'Workflow started'), ('WORKFLOW_APPROVED', 'Workflow approved'), ('WORKFLOW_REJECTED', 'Workflow rejected'), ('WORKFLOW_CHANGES_REQUESTED', 'Workflow changes requested'), ('WORKFLOW_COMMENTED', 'Workflow commented')], max_length=40, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('IN_REVIEW', 'In review'), ('CHANGES_REQUESTED', 'Changes requested'), ('REJECTED', 'Rejected'), ('APPROVED', 'Актуальный'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_templates', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Workflow template',
                'verbose_name_plural': 'Workflow templates',
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='Instructions')),
                ('approver_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_step_templates', to='dms.department', verbose_name='Approver department')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_step_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Approver user')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dms.workflowtemplate', verbose_name='Workflow template')),
            ],
            options={
                'verbose_name': 'Workflow step template',
                'verbose_name_plural': 'Workflow step templates',
                'ordering': ['template', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes requested'), ('CANCELED', 'Canceled')], db_index=True, default='ACTIVE', max_length=30, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='dms.document', verbose_name='Document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='dms.organization', verbose_name='Organization')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_workflow_instances', to=settings.AUTH_USER_MODEL, verbose_name='Started by')),
                ('current_step_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_instances', to='dms.workflowsteptemplate', verbose_name='Current step')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='dms.workflowtemplate', verbose_name='Workflow template')),
            ],
            options={
                'verbose_name': 'Workflow instance',
                'verbose_name_plural': 'Workflow instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('START', 'Start'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_CHANGES', 'Request changes'), ('COMMENT', 'Comment')], db_index=True, max_length=30, verbose_name='Action')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='dms.document', verbose_name='Document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_actions', to='dms.organization', verbose_name='Organization')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dms.workflowinstance', verbose_name='Workflow instance')),
                ('step_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='dms.workflowsteptemplate', verbose_name='Workflow step')),
            ],
            options={
                'verbose_name': 'Workflow action',
                'verbose_name_plural': 'Workflow actions',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='dms_workflo_organiz_be3f33_idx'), models.Index(fields=['instance', 'created_at'], name='dms_workflo_instanc_8315c7_idx'), models.Index(fields=['document', '-created_at'], name='dms_workflo_documen_3cfa58_idx'), models.Index(fields=['actor', '-created_at'], name='dms_workflo_actor_i_2800cf_idx'), models.Index(fields=['action_type', '-created_at'], name='dms_workflo_action__c523cc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['organization', 'is_active'], name='dms_workflo_organiz_4b3913_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_workflow_template_name_per_organization'),
        ),
        migrations.AddIndex(
            model_name='workflowsteptemplate',
            index=models.Index(fields=['template', 'order'], name='dms_workflo_templat_be099d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowsteptemplate',
            index=models.Index(fields=['approver_user'], name='dms_workflo_approve_cbd7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowsteptemplate',
            index=models.Index(fields=['approver_department'], name='dms_workflo_approve_406262_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowsteptemplate',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_workflow_step_order_per_template'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['organization', 'status', '-started_at'], name='dms_workflo_organiz_d216fe_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['document', 'status'], name='dms_workflo_documen_32dd17_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['current_step_template', 'status'], name='dms_workflo_current_9bece2_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('document',), name='unique_active_workflow_per_document'),
        ),
    ]
