# Generated by Django 6.0.1 on 2026-05-11 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0024_alter_auditevent_event_type_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Документ загружен'), ('DOCUMENT_UPDATED', 'Документ обновлен'), ('DOCUMENT_VIEWED', 'Документ просмотрен'), ('DOCUMENT_DOWNLOADED', 'Документ скачан'), ('DOCUMENT_VERSION_VIEWED', 'Версия документа просмотрена'), ('DOCUMENT_VERSION_DOWNLOADED', 'Версия документа скачана'), ('DOCUMENT_DELETED', 'Документ удален'), ('DOCUMENT_ACCESS_GRANTED', 'Доступ к документу выдан'), ('DOCUMENT_ACCESS_REVOKED', 'Доступ к документу отозван'), ('DOCUMENT_STATUS_CHANGED', 'Статус документа изменен'), ('AI_PROCESSING_STARTED', 'AI-обработка начата'), ('AI_PROCESSING_COMPLETED', 'AI-обработка завершена'), ('AI_PROCESSING_FAILED', 'AI-обработка завершилась ошибкой'), ('AI_FIELD_CONFIRMED', 'AI-поле подтверждено'), ('AI_FIELD_REJECTED', 'AI-поле отклонено'), ('AI_FIELDS_APPLIED', 'AI-поля применены к документу'), ('IMPORT_BATCH_CREATED', 'Партия импорта создана'), ('IMPORT_FILE_IMPORTED', 'Файл импортирован'), ('IMPORT_FILE_DUPLICATE', 'Дубликат при импорте'), ('IMPORT_FILE_FAILED', 'Ошибка импорта файла'), ('WORKFLOW_STARTED', 'Workflow started'), ('WORKFLOW_APPROVED', 'Workflow approved'), ('WORKFLOW_REJECTED', 'Workflow rejected'), ('WORKFLOW_CHANGES_REQUESTED', 'Workflow changes requested'), ('WORKFLOW_COMMENTED', 'Workflow commented'), ('WORKFLOW_COMPLETED', 'Workflow completed'), ('EXCHANGE_SENT', 'Document exchange sent'), ('EXCHANGE_OPENED', 'Document exchange opened'), ('EXCHANGE_DOWNLOADED', 'Document exchange downloaded'), ('EXCHANGE_ACCEPTED', 'Document exchange accepted'), ('EXCHANGE_REJECTED', 'Document exchange rejected'), ('EXCHANGE_COMMENTED', 'Document exchange commented')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('contact_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Contact name')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counterparties', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparties', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Counterparty',
                'verbose_name_plural': 'Counterparties',
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('OPENED', 'Opened'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='SENT', max_length=20, verbose_name='Status')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token hash')),
                ('token_hint', models.CharField(blank=True, default='', max_length=12, verbose_name='Token hint')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Opened at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_exchanges', to='dms.counterparty', verbose_name='Counterparty')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='dms.document', verbose_name='Document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_exchanges', to='dms.organization', verbose_name='Organization')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_document_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Sent by')),
            ],
            options={
                'verbose_name': 'Document exchange',
                'verbose_name_plural': 'Document exchanges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SENT', 'Sent'), ('OPENED', 'Opened'), ('DOWNLOADED', 'Downloaded'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMMENTED', 'Commented'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, max_length=20, verbose_name='Event type')),
                ('actor_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Actor name')),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Actor email')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_events', to='dms.document', verbose_name='Document')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dms.documentexchange', verbose_name='Document exchange')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_events', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Exchange event',
                'verbose_name_plural': 'Exchange events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['organization', 'is_active'], name='dms_counter_organiz_1c2b73_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['email'], name='dms_counter_email_195e8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_counterparty_name_per_organization'),
        ),
        migrations.AddIndex(
            model_name='documentexchange',
            index=models.Index(fields=['organization', '-created_at'], name='dms_documen_organiz_a843bc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentexchange',
            index=models.Index(fields=['document', '-created_at'], name='dms_documen_documen_df8930_idx'),
        ),
        migrations.AddIndex(
            model_name='documentexchange',
            index=models.Index(fields=['counterparty', '-created_at'], name='dms_documen_counter_b4db55_idx'),
        ),
        migrations.AddIndex(
            model_name='documentexchange',
            index=models.Index(fields=['status', '-created_at'], name='dms_documen_status_a53a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentexchange',
            index=models.Index(fields=['expires_at'], name='dms_documen_expires_952b36_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeevent',
            index=models.Index(fields=['organization', '-created_at'], name='dms_exchang_organiz_20e9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeevent',
            index=models.Index(fields=['exchange', '-created_at'], name='dms_exchang_exchang_0f9f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeevent',
            index=models.Index(fields=['document', '-created_at'], name='dms_exchang_documen_0d2235_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeevent',
            index=models.Index(fields=['event_type', '-created_at'], name='dms_exchang_event_t_8347b7_idx'),
        ),
    ]
