# Generated by Django 6.0.1 on 2026-05-11 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0025_alter_auditevent_event_type_counterparty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentexchange',
            name='business_document_type',
            field=models.CharField(blank=True, choices=[('CONTRACT', 'Contract'), ('INVOICE', 'Invoice'), ('ACT', 'Act'), ('LETTER', 'Letter'), ('OTHER', 'Other')], db_index=True, default='', max_length=40, verbose_name='Business document type'),
        ),
        migrations.AddField(
            model_name='documentexchange',
            name='direction',
            field=models.CharField(choices=[('OUTGOING', 'Outgoing'), ('INCOMING', 'Incoming')], db_index=True, default='OUTGOING', max_length=20, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='documentexchange',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Received at'),
        ),
        migrations.AddField(
            model_name='documentexchange',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_document_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Received by'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Документ загружен'), ('DOCUMENT_UPDATED', 'Документ обновлен'), ('DOCUMENT_VIEWED', 'Документ просмотрен'), ('DOCUMENT_DOWNLOADED', 'Документ скачан'), ('DOCUMENT_VERSION_VIEWED', 'Версия документа просмотрена'), ('DOCUMENT_VERSION_DOWNLOADED', 'Версия документа скачана'), ('DOCUMENT_DELETED', 'Документ удален'), ('DOCUMENT_ACCESS_GRANTED', 'Доступ к документу выдан'), ('DOCUMENT_ACCESS_REVOKED', 'Доступ к документу отозван'), ('DOCUMENT_STATUS_CHANGED', 'Статус документа изменен'), ('AI_PROCESSING_STARTED', 'AI-обработка начата'), ('AI_PROCESSING_COMPLETED', 'AI-обработка завершена'), ('AI_PROCESSING_FAILED', 'AI-обработка завершилась ошибкой'), ('AI_FIELD_CONFIRMED', 'AI-поле подтверждено'), ('AI_FIELD_REJECTED', 'AI-поле отклонено'), ('AI_FIELDS_APPLIED', 'AI-поля применены к документу'), ('IMPORT_BATCH_CREATED', 'Партия импорта создана'), ('IMPORT_FILE_IMPORTED', 'Файл импортирован'), ('IMPORT_FILE_DUPLICATE', 'Дубликат при импорте'), ('IMPORT_FILE_FAILED', 'Ошибка импорта файла'), ('WORKFLOW_STARTED', 'Workflow started'), ('WORKFLOW_APPROVED', 'Workflow approved'), ('WORKFLOW_REJECTED', 'Workflow rejected'), ('WORKFLOW_CHANGES_REQUESTED', 'Workflow changes requested'), ('WORKFLOW_COMMENTED', 'Workflow commented'), ('WORKFLOW_COMPLETED', 'Workflow completed'), ('EXCHANGE_SENT', 'Document exchange sent'), ('EXCHANGE_OPENED', 'Document exchange opened'), ('EXCHANGE_DOWNLOADED', 'Document exchange downloaded'), ('EXCHANGE_ACCEPTED', 'Document exchange accepted'), ('EXCHANGE_REJECTED', 'Document exchange rejected'), ('EXCHANGE_COMMENTED', 'Document exchange commented'), ('EXCHANGE_RECEIVED', 'B2B document exchange received')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='documentexchange',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('OPENED', 'Opened'), ('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='SENT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='exchangeevent',
            name='event_type',
            field=models.CharField(choices=[('SENT', 'Sent'), ('OPENED', 'Opened'), ('DOWNLOADED', 'Downloaded'), ('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMMENTED', 'Commented'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, max_length=20, verbose_name='Event type'),
        ),
        migrations.AddIndex(
            model_name='documentexchange',
            index=models.Index(fields=['direction', 'status', '-created_at'], name='dms_documen_directi_5a5561_idx'),
        ),
        migrations.AddIndex(
            model_name='documentexchange',
            index=models.Index(fields=['business_document_type', '-created_at'], name='dms_documen_busines_53448e_idx'),
        ),
    ]
