# Generated by Django 6.0.1 on 2026-05-11 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0026_documentexchange_business_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], db_index=True, max_length=20, verbose_name='Author type')),
                ('body', models.TextField(verbose_name='Body')),
                ('source_event_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Source event type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Exchange message',
                'verbose_name_plural': 'Exchange messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CounterpartyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='Position')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Phone')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dms.counterparty', verbose_name='Counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counterparty_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Counterparty contact',
                'verbose_name_plural': 'Counterparty contacts',
                'ordering': ['counterparty__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='documentexchange',
            name='counterparty_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_exchanges', to='dms.counterpartycontact', verbose_name='Counterparty contact'),
        ),
        migrations.AddIndex(
            model_name='documentexchange',
            index=models.Index(fields=['counterparty_contact', '-created_at'], name='dms_documen_counter_3aea5a_idx'),
        ),
        migrations.AddField(
            model_name='exchangemessage',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_messages', to='dms.counterparty', verbose_name='Counterparty'),
        ),
        migrations.AddField(
            model_name='exchangemessage',
            name='counterparty_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_messages', to='dms.counterpartycontact', verbose_name='Counterparty contact'),
        ),
        migrations.AddField(
            model_name='exchangemessage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_messages', to='dms.document', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='exchangemessage',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dms.documentexchange', verbose_name='Document exchange'),
        ),
        migrations.AddField(
            model_name='exchangemessage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_messages', to='dms.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='exchangemessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_messages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='counterpartycontact',
            index=models.Index(fields=['counterparty', 'is_active'], name='dms_counter_counter_bc097b_idx'),
        ),
        migrations.AddIndex(
            model_name='counterpartycontact',
            index=models.Index(fields=['email'], name='dms_counter_email_5aea63_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangemessage',
            index=models.Index(fields=['organization', '-created_at'], name='dms_exchang_organiz_801800_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangemessage',
            index=models.Index(fields=['exchange', 'created_at'], name='dms_exchang_exchang_8c3ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangemessage',
            index=models.Index(fields=['document', '-created_at'], name='dms_exchang_documen_cdec5a_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangemessage',
            index=models.Index(fields=['counterparty', '-created_at'], name='dms_exchang_counter_30805e_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangemessage',
            index=models.Index(fields=['author_type', '-created_at'], name='dms_exchang_author__3df756_idx'),
        ),
    ]
