# Generated by Django 6.0.1 on 2026-05-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0027_exchangemessage_counterpartycontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('document.uploaded', 'Document uploaded'), ('import.batch_created', 'Import batch created'), ('import.file_imported', 'Import file imported'), ('import.file_duplicate', 'Import file duplicate'), ('import.file_failed', 'Import file failed'), ('ai.processing_started', 'AI processing started'), ('ai.processing_completed', 'AI processing completed'), ('ai.processing_failed', 'AI processing failed'), ('workflow.started', 'Workflow started'), ('workflow.action', 'Workflow action'), ('exchange.event', 'Exchange event'), ('evidence.exported', 'Evidence exported')], db_index=True, max_length=80, verbose_name='Event type')),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='Source')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='dms.document', verbose_name='Document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='dms.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Usage event',
                'verbose_name_plural': 'Usage events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('event_types', models.JSONField(blank=True, default=list, verbose_name='Event types')),
                ('secret_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='Secret hash')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhook_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_endpoints', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Webhook endpoint',
                'verbose_name_plural': 'Webhook endpoints',
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=80, verbose_name='Event type')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempt count')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Next attempt at')),
                ('response_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Response status')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_deliveries', to='dms.organization', verbose_name='Organization')),
                ('usage_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='dms.usageevent', verbose_name='Usage event')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='dms.webhookendpoint', verbose_name='Webhook endpoint')),
            ],
            options={
                'verbose_name': 'Webhook delivery',
                'verbose_name_plural': 'Webhook deliveries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['organization', '-created_at'], name='dms_usageev_organiz_032d89_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['organization', 'event_type', '-created_at'], name='dms_usageev_organiz_918bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['document', '-created_at'], name='dms_usageev_documen_511c58_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', '-created_at'], name='dms_usageev_user_id_1bace7_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['organization', 'is_active'], name='dms_webhook_organiz_09d553_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['organization', '-created_at'], name='dms_webhook_organiz_f4d389_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'status', '-created_at'], name='dms_webhook_endpoin_afa078_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['usage_event', '-created_at'], name='dms_webhook_usage_e_aef56e_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['event_type', '-created_at'], name='dms_webhook_event_t_5425e5_idx'),
        ),
    ]
