# Generated by Django 6.0.1 on 2026-05-11 18:21

import django.db.models.deletion
import dms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0028_usageevent_webhookendpoint_webhookdelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('provider_type', models.CharField(choices=[('email', 'Email'), ('1c', '1C'), ('google_drive', 'Google Drive'), ('onedrive', 'OneDrive'), ('sharepoint', 'SharePoint'), ('external_api', 'External API'), ('other', 'Other')], db_index=True, max_length=40, verbose_name='Provider type')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Integration provider',
                'verbose_name_plural': 'Integration providers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Документ загружен'), ('DOCUMENT_UPDATED', 'Документ обновлен'), ('DOCUMENT_VIEWED', 'Документ просмотрен'), ('DOCUMENT_DOWNLOADED', 'Документ скачан'), ('DOCUMENT_VERSION_VIEWED', 'Версия документа просмотрена'), ('DOCUMENT_VERSION_DOWNLOADED', 'Версия документа скачана'), ('DOCUMENT_DELETED', 'Документ удален'), ('DOCUMENT_ACCESS_GRANTED', 'Доступ к документу выдан'), ('DOCUMENT_ACCESS_REVOKED', 'Доступ к документу отозван'), ('DOCUMENT_STATUS_CHANGED', 'Статус документа изменен'), ('AI_PROCESSING_STARTED', 'AI-обработка начата'), ('AI_PROCESSING_COMPLETED', 'AI-обработка завершена'), ('AI_PROCESSING_FAILED', 'AI-обработка завершилась ошибкой'), ('AI_FIELD_CONFIRMED', 'AI-поле подтверждено'), ('AI_FIELD_REJECTED', 'AI-поле отклонено'), ('AI_FIELDS_APPLIED', 'AI-поля применены к документу'), ('IMPORT_BATCH_CREATED', 'Партия импорта создана'), ('IMPORT_FILE_IMPORTED', 'Файл импортирован'), ('IMPORT_FILE_DUPLICATE', 'Дубликат при импорте'), ('IMPORT_FILE_FAILED', 'Ошибка импорта файла'), ('WORKFLOW_STARTED', 'Workflow started'), ('WORKFLOW_APPROVED', 'Workflow approved'), ('WORKFLOW_REJECTED', 'Workflow rejected'), ('WORKFLOW_CHANGES_REQUESTED', 'Workflow changes requested'), ('WORKFLOW_COMMENTED', 'Workflow commented'), ('WORKFLOW_COMPLETED', 'Workflow completed'), ('EXCHANGE_SENT', 'Document exchange sent'), ('EXCHANGE_OPENED', 'Document exchange opened'), ('EXCHANGE_DOWNLOADED', 'Document exchange downloaded'), ('EXCHANGE_ACCEPTED', 'Document exchange accepted'), ('EXCHANGE_REJECTED', 'Document exchange rejected'), ('EXCHANGE_COMMENTED', 'Document exchange commented'), ('EXCHANGE_RECEIVED', 'B2B document exchange received'), ('INTEGRATION_CONNECTION_CREATED', 'Integration connection created'), ('INTEGRATION_SYNC_JOB_CREATED', 'Integration sync job created'), ('EXTERNAL_REFERENCE_LINKED', 'External reference linked')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='event_type',
            field=models.CharField(choices=[('document.uploaded', 'Document uploaded'), ('import.batch_created', 'Import batch created'), ('import.file_imported', 'Import file imported'), ('import.file_duplicate', 'Import file duplicate'), ('import.file_failed', 'Import file failed'), ('ai.processing_started', 'AI processing started'), ('ai.processing_completed', 'AI processing completed'), ('ai.processing_failed', 'AI processing failed'), ('workflow.started', 'Workflow started'), ('workflow.action', 'Workflow action'), ('exchange.event', 'Exchange event'), ('evidence.exported', 'Evidence exported'), ('integration.connection_created', 'Integration connection created'), ('integration.sync_job_created', 'Integration sync job created'), ('integration.external_reference_linked', 'External reference linked')], db_index=True, max_length=80, verbose_name='Event type'),
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ERROR', 'Error'), ('DISABLED', 'Disabled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('credentials_metadata', models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Credentials metadata')),
                ('secret_ref', models.CharField(blank=True, default='', max_length=255, verbose_name='Secret reference')),
                ('settings', models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Settings')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last sync at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integration_connections', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_connections', to='dms.organization', verbose_name='Organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='dms.integrationprovider', verbose_name='Integration provider')),
            ],
            options={
                'verbose_name': 'Integration connection',
                'verbose_name_plural': 'Integration connections',
                'ordering': ['organization__name', 'provider__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total items')),
                ('processed_items', models.PositiveIntegerField(default=0, verbose_name='Processed items')),
                ('created_documents', models.PositiveIntegerField(default=0, verbose_name='Created documents')),
                ('linked_references', models.PositiveIntegerField(default=0, verbose_name='Linked references')),
                ('failed_items', models.PositiveIntegerField(default=0, verbose_name='Failed items')),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Metadata')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='dms.integrationconnection', verbose_name='Integration connection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_sync_jobs', to='dms.organization', verbose_name='Organization')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_integration_sync_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Started by')),
            ],
            options={
                'verbose_name': 'Integration sync job',
                'verbose_name_plural': 'Integration sync jobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=512, verbose_name='External ID')),
                ('external_type', models.CharField(blank=True, default='', max_length=80, verbose_name='External type')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Display name')),
                ('external_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='External URL')),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Metadata')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='First seen at')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Last seen at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_references', to='dms.document', verbose_name='Document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='dms.organization', verbose_name='Organization')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_references', to='dms.integrationconnection', verbose_name='Integration connection')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='dms.integrationprovider', verbose_name='Integration provider')),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_references', to='dms.integrationsyncjob', verbose_name='Integration sync job')),
            ],
            options={
                'verbose_name': 'External reference',
                'verbose_name_plural': 'External references',
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['organization', 'status'], name='dms_integra_organiz_a93d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['provider', 'status'], name='dms_integra_provide_a821f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'name'), name='unique_integration_connection_name_per_provider'),
        ),
        migrations.AddIndex(
            model_name='integrationsyncjob',
            index=models.Index(fields=['organization', '-created_at'], name='dms_integra_organiz_de6a25_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsyncjob',
            index=models.Index(fields=['connection', 'status', '-created_at'], name='dms_integra_connect_7db3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsyncjob',
            index=models.Index(fields=['status', '-created_at'], name='dms_integra_status_6b53ab_idx'),
        ),
        migrations.AddIndex(
            model_name='externalreference',
            index=models.Index(fields=['organization', '-last_seen_at'], name='dms_externa_organiz_da24a8_idx'),
        ),
        migrations.AddIndex(
            model_name='externalreference',
            index=models.Index(fields=['document', '-last_seen_at'], name='dms_externa_documen_840bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='externalreference',
            index=models.Index(fields=['provider', 'external_type'], name='dms_externa_provide_15f314_idx'),
        ),
        migrations.AddIndex(
            model_name='externalreference',
            index=models.Index(fields=['connection', 'external_type'], name='dms_externa_connect_4ed2fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalreference',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='unique_external_reference_per_connection'),
        ),
    ]
