# Generated by Django 6.0.1 on 2026-05-11 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0030_seed_integration_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('billing_interval', models.CharField(choices=[('manual', 'Manual'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='manual', max_length=20, verbose_name='Billing interval')),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price amount')),
                ('currency', models.CharField(default='KZT', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Документ загружен'), ('DOCUMENT_UPDATED', 'Документ обновлен'), ('DOCUMENT_VIEWED', 'Документ просмотрен'), ('DOCUMENT_DOWNLOADED', 'Документ скачан'), ('DOCUMENT_VERSION_VIEWED', 'Версия документа просмотрена'), ('DOCUMENT_VERSION_DOWNLOADED', 'Версия документа скачана'), ('DOCUMENT_DELETED', 'Документ удален'), ('DOCUMENT_ACCESS_GRANTED', 'Доступ к документу выдан'), ('DOCUMENT_ACCESS_REVOKED', 'Доступ к документу отозван'), ('DOCUMENT_STATUS_CHANGED', 'Статус документа изменен'), ('AI_PROCESSING_STARTED', 'AI-обработка начата'), ('AI_PROCESSING_COMPLETED', 'AI-обработка завершена'), ('AI_PROCESSING_FAILED', 'AI-обработка завершилась ошибкой'), ('AI_FIELD_CONFIRMED', 'AI-поле подтверждено'), ('AI_FIELD_REJECTED', 'AI-поле отклонено'), ('AI_FIELDS_APPLIED', 'AI-поля применены к документу'), ('IMPORT_BATCH_CREATED', 'Партия импорта создана'), ('IMPORT_FILE_IMPORTED', 'Файл импортирован'), ('IMPORT_FILE_DUPLICATE', 'Дубликат при импорте'), ('IMPORT_FILE_FAILED', 'Ошибка импорта файла'), ('WORKFLOW_STARTED', 'Workflow started'), ('WORKFLOW_APPROVED', 'Workflow approved'), ('WORKFLOW_REJECTED', 'Workflow rejected'), ('WORKFLOW_CHANGES_REQUESTED', 'Workflow changes requested'), ('WORKFLOW_COMMENTED', 'Workflow commented'), ('WORKFLOW_COMPLETED', 'Workflow completed'), ('EXCHANGE_SENT', 'Document exchange sent'), ('EXCHANGE_OPENED', 'Document exchange opened'), ('EXCHANGE_DOWNLOADED', 'Document exchange downloaded'), ('EXCHANGE_ACCEPTED', 'Document exchange accepted'), ('EXCHANGE_REJECTED', 'Document exchange rejected'), ('EXCHANGE_COMMENTED', 'Document exchange commented'), ('EXCHANGE_RECEIVED', 'B2B document exchange received'), ('INTEGRATION_CONNECTION_CREATED', 'Integration connection created'), ('INTEGRATION_SYNC_JOB_CREATED', 'Integration sync job created'), ('EXTERNAL_REFERENCE_LINKED', 'External reference linked'), ('BILLING_SUBSCRIPTION_CREATED', 'Billing subscription created')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='PlanQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_event_type', models.CharField(choices=[('document.uploaded', 'Document uploaded'), ('import.batch_created', 'Import batch created'), ('import.file_imported', 'Import file imported'), ('import.file_duplicate', 'Import file duplicate'), ('import.file_failed', 'Import file failed'), ('ai.processing_started', 'AI processing started'), ('ai.processing_completed', 'AI processing completed'), ('ai.processing_failed', 'AI processing failed'), ('workflow.started', 'Workflow started'), ('workflow.action', 'Workflow action'), ('exchange.event', 'Exchange event'), ('evidence.exported', 'Evidence exported'), ('integration.connection_created', 'Integration connection created'), ('integration.sync_job_created', 'Integration sync job created'), ('integration.external_reference_linked', 'External reference linked')], db_index=True, max_length=80, verbose_name='Usage event type')),
                ('limit', models.PositiveIntegerField(default=0, verbose_name='Limit')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Unlimited')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='dms.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan quota',
                'verbose_name_plural': 'Plan quotas',
                'ordering': ['plan__name', 'usage_event_type'],
                'indexes': [models.Index(fields=['plan', 'usage_event_type'], name='dms_planquo_plan_id_94687e_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'usage_event_type'), name='unique_plan_quota_per_event_type')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIALING', 'Trialing'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('current_period_start', models.DateField(blank=True, null=True, verbose_name='Current period start')),
                ('current_period_end', models.DateField(blank=True, null=True, verbose_name='Current period end')),
                ('is_default', models.BooleanField(default=True, verbose_name='Default subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='dms.organization', verbose_name='Organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='dms.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['organization__name'],
                'indexes': [models.Index(fields=['plan', 'status'], name='dms_subscri_plan_id_ef4ad6_idx'), models.Index(fields=['status', 'current_period_end'], name='dms_subscri_status_437ac4_idx')],
            },
        ),
    ]
