# Generated by Django 6.0.1 on 2026-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0032_seed_billing_plans_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_RELATION_CREATED', 'Document relation created'), ('DOCUMENT_RELATION_DELETED', 'Document relation deleted'), ('DOCUMENT_UPLOADED', 'Документ загружен'), ('DOCUMENT_UPDATED', 'Документ обновлен'), ('DOCUMENT_VIEWED', 'Документ просмотрен'), ('DOCUMENT_DOWNLOADED', 'Документ скачан'), ('DOCUMENT_VERSION_VIEWED', 'Версия документа просмотрена'), ('DOCUMENT_VERSION_DOWNLOADED', 'Версия документа скачана'), ('DOCUMENT_DELETED', 'Документ удален'), ('DOCUMENT_ACCESS_GRANTED', 'Доступ к документу выдан'), ('DOCUMENT_ACCESS_REVOKED', 'Доступ к документу отозван'), ('DOCUMENT_STATUS_CHANGED', 'Статус документа изменен'), ('AI_PROCESSING_STARTED', 'AI-обработка начата'), ('AI_PROCESSING_COMPLETED', 'AI-обработка завершена'), ('AI_PROCESSING_FAILED', 'AI-обработка завершилась ошибкой'), ('AI_FIELD_CONFIRMED', 'AI-поле подтверждено'), ('AI_FIELD_REJECTED', 'AI-поле отклонено'), ('AI_FIELDS_APPLIED', 'AI-поля применены к документу'), ('IMPORT_BATCH_CREATED', 'Партия импорта создана'), ('IMPORT_FILE_IMPORTED', 'Файл импортирован'), ('IMPORT_FILE_DUPLICATE', 'Дубликат при импорте'), ('IMPORT_FILE_FAILED', 'Ошибка импорта файла'), ('WORKFLOW_STARTED', 'Workflow started'), ('WORKFLOW_APPROVED', 'Workflow approved'), ('WORKFLOW_REJECTED', 'Workflow rejected'), ('WORKFLOW_CHANGES_REQUESTED', 'Workflow changes requested'), ('WORKFLOW_COMMENTED', 'Workflow commented'), ('WORKFLOW_COMPLETED', 'Workflow completed'), ('EXCHANGE_SENT', 'Document exchange sent'), ('EXCHANGE_OPENED', 'Document exchange opened'), ('EXCHANGE_DOWNLOADED', 'Document exchange downloaded'), ('EXCHANGE_ACCEPTED', 'Document exchange accepted'), ('EXCHANGE_REJECTED', 'Document exchange rejected'), ('EXCHANGE_COMMENTED', 'Document exchange commented'), ('EXCHANGE_RECEIVED', 'B2B document exchange received'), ('INTEGRATION_CONNECTION_CREATED', 'Integration connection created'), ('INTEGRATION_SYNC_JOB_CREATED', 'Integration sync job created'), ('EXTERNAL_REFERENCE_LINKED', 'External reference linked'), ('BILLING_SUBSCRIPTION_CREATED', 'Billing subscription created')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='documentrelation',
            name='relation_type',
            field=models.CharField(choices=[('REPLACED_BY', 'Replaced by'), ('PRIMARY_DOCUMENT', 'Primary document'), ('ADDENDUM', 'Addendum'), ('ACT', 'Act'), ('INVOICE', 'Invoice'), ('SIGNED_SCAN', 'Signed scan'), ('REVISION', 'Revision'), ('OTHER', 'Other'), ('REPLACES', 'Заменяет'), ('APPENDIX_TO', 'Приложение к'), ('RELATED_TO', 'Связан с'), ('MENTIONS', 'Упоминает')], max_length=20, verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='planquota',
            name='usage_event_type',
            field=models.CharField(choices=[('document.relation_created', 'Document relation created'), ('document.relation_deleted', 'Document relation deleted'), ('document.uploaded', 'Document uploaded'), ('import.batch_created', 'Import batch created'), ('import.file_imported', 'Import file imported'), ('import.file_duplicate', 'Import file duplicate'), ('import.file_failed', 'Import file failed'), ('ai.processing_started', 'AI processing started'), ('ai.processing_completed', 'AI processing completed'), ('ai.processing_failed', 'AI processing failed'), ('workflow.started', 'Workflow started'), ('workflow.action', 'Workflow action'), ('exchange.event', 'Exchange event'), ('evidence.exported', 'Evidence exported'), ('integration.connection_created', 'Integration connection created'), ('integration.sync_job_created', 'Integration sync job created'), ('integration.external_reference_linked', 'External reference linked')], db_index=True, max_length=80, verbose_name='Usage event type'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='event_type',
            field=models.CharField(choices=[('document.relation_created', 'Document relation created'), ('document.relation_deleted', 'Document relation deleted'), ('document.uploaded', 'Document uploaded'), ('import.batch_created', 'Import batch created'), ('import.file_imported', 'Import file imported'), ('import.file_duplicate', 'Import file duplicate'), ('import.file_failed', 'Import file failed'), ('ai.processing_started', 'AI processing started'), ('ai.processing_completed', 'AI processing completed'), ('ai.processing_failed', 'AI processing failed'), ('workflow.started', 'Workflow started'), ('workflow.action', 'Workflow action'), ('exchange.event', 'Exchange event'), ('evidence.exported', 'Evidence exported'), ('integration.connection_created', 'Integration connection created'), ('integration.sync_job_created', 'Integration sync job created'), ('integration.external_reference_linked', 'External reference linked')], db_index=True, max_length=80, verbose_name='Event type'),
        ),
    ]
