# Generated by Django 6.0.1 on 2026-05-12 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0034_exchange_maturity_audit_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('WORKFLOW_ASSIGNED', 'Workflow assigned'), ('AI_REVIEW_READY', 'AI review ready'), ('EXCHANGE_OPENED', 'Exchange opened'), ('EXCHANGE_COMMENTED', 'Exchange commented'), ('EXCHANGE_ACCEPTED', 'Exchange accepted'), ('EXCHANGE_REJECTED', 'Exchange rejected')], db_index=True, max_length=40, verbose_name='Notification type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='dms.organization', verbose_name='Organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='dms.document', verbose_name='Related document')),
                ('related_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='dms.documentexchange', verbose_name='Related exchange')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='dms_notific_recipie_566193_idx'), models.Index(fields=['organization', '-created_at'], name='dms_notific_organiz_ce711c_idx'), models.Index(fields=['related_document', '-created_at'], name='dms_notific_related_4e15e0_idx'), models.Index(fields=['related_exchange', '-created_at'], name='dms_notific_related_11df4c_idx')],
            },
        ),
    ]
