# Generated by Django 6.0.1 on 2026-05-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0035_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='search_embedding_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='search_entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='search_index_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='search_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='search_text_normalized',
            field=models.TextField(blank=True, default=''),
        ),
    ]
