# Generated by Django 6.0.1 on 2026-05-17 17:33

import django.db.models.deletion
import django.utils.timezone
import dms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0036_document_search_intelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Attempt count'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='center_metadata',
            field=models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Processing center metadata'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Idempotency key'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='lock_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Lock token'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked at'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='Max attempts'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Next retry at'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_jobs', to='dms.processingjob', verbose_name='Parent processing job'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='pipeline_stage',
            field=models.CharField(choices=[('AI_PARSE', 'AI parse'), ('OCR', 'OCR'), ('TEXT_EXTRACTION', 'Text extraction'), ('ENTITY_EXTRACTION', 'Entity extraction'), ('CHUNKING', 'Chunking'), ('EMBEDDING', 'Embedding'), ('RERANKING', 'Reranking'), ('REINDEX', 'Reindex'), ('FAN_OUT', 'Fan out'), ('FAN_IN', 'Fan in')], db_index=True, default='AI_PARSE', max_length=40, verbose_name='Pipeline stage'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=5, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Scheduled at'),
        ),
        migrations.CreateModel(
            name='ProcessingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('code', models.SlugField(max_length=80, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('max_concurrent_jobs', models.PositiveIntegerField(default=2, verbose_name='Max concurrent jobs')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Max attempts')),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=300, verbose_name='Retry backoff seconds')),
                ('allowed_stages', models.JSONField(blank=True, default=list, verbose_name='Allowed stages')),
                ('config', models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Config')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organization', models.ForeignKey(blank=True, help_text='Empty organization means a global reusable profile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_profiles', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Processing profile',
                'verbose_name_plural': 'Processing profiles',
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='processingjob',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='dms.processingprofile', verbose_name='Processing profile'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'scheduled_at', 'priority'], name='dms_process_status_b589b1_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['pipeline_stage', 'status'], name='dms_process_pipelin_847d41_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['parent_job', 'status'], name='dms_process_parent__db68c0_idx'),
        ),
        migrations.AddIndex(
            model_name='processingprofile',
            index=models.Index(fields=['organization', 'is_active'], name='dms_process_organiz_16b922_idx'),
        ),
        migrations.AddIndex(
            model_name='processingprofile',
            index=models.Index(fields=['code', 'is_active'], name='dms_process_code_fdb8e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_processing_profile_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='processingprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='unique_global_processing_profile_code'),
        ),
    ]
