# Generated by Django 6.0.1 on 2026-05-17 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0037_processing_center_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndexVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_model', models.CharField(max_length=255, verbose_name='Embedding model')),
                ('embedding_dimension', models.PositiveIntegerField(verbose_name='Embedding dimension')),
                ('chunking_version', models.CharField(default='chunking-v1', max_length=40, verbose_name='Chunking version')),
                ('normalization_version', models.CharField(default='normalization-v1', max_length=40, verbose_name='Normalization version')),
                ('qdrant_collection', models.CharField(max_length=255, verbose_name='Qdrant collection')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Search index version',
                'verbose_name_plural': 'Search index versions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['is_active', 'qdrant_collection'], name='dms_searchi_is_acti_6b8d99_idx'), models.Index(fields=['embedding_model', 'embedding_dimension'], name='dms_searchi_embeddi_14f880_idx')],
                'constraints': [models.UniqueConstraint(fields=('embedding_model', 'embedding_dimension', 'chunking_version', 'normalization_version', 'qdrant_collection'), name='unique_search_index_version_config')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSearchIndexState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INDEXED', 'Indexed'), ('STALE', 'Stale'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='Indexed at')),
                ('chunks_count', models.PositiveIntegerField(default=0, verbose_name='Chunks count')),
                ('qdrant_collection', models.CharField(max_length=255, verbose_name='Qdrant collection')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Content hash')),
                ('point_ids', models.JSONField(blank=True, default=list, verbose_name='Qdrant point IDs')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last error')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_index_states', to='dms.document', verbose_name='Document')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_index_states', to='dms.documentversion', verbose_name='Document version')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_search_index_states', to='dms.organization', verbose_name='Organization')),
                ('index_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_states', to='dms.searchindexversion', verbose_name='Search index version')),
            ],
            options={
                'verbose_name': 'Document search index state',
                'verbose_name_plural': 'Document search index states',
                'ordering': ['document_id', '-updated_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='dms_documen_organiz_8050dc_idx'), models.Index(fields=['document', 'status'], name='dms_documen_documen_0c427c_idx'), models.Index(fields=['index_version', 'status'], name='dms_documen_index_v_92eb47_idx'), models.Index(fields=['qdrant_collection', 'status'], name='dms_documen_qdrant__e45628_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'index_version'), name='unique_document_search_index_state')],
            },
        ),
    ]
