# Generated by Django 6.0.1 on 2026-05-17 21:19

import django.db.models.deletion
import dms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0038_incremental_indexing_vector_versioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservabilityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, max_length=120, verbose_name='Alert type')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20, verbose_name='Severity')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('details', models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Details')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Triggered at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved at')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observability_alerts', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Observability alert',
                'verbose_name_plural': 'Observability alerts',
                'ordering': ['-triggered_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status', '-triggered_at'], name='dms_observa_organiz_b67c5c_idx'), models.Index(fields=['alert_type', 'status'], name='dms_observa_alert_t_155b6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ObservabilityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('processing', 'Processing'), ('queue', 'Queue'), ('search', 'Search'), ('gpu', 'GPU'), ('qdrant', 'Qdrant'), ('reindex', 'Reindex')], db_index=True, max_length=40, verbose_name='Category')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Metric name')),
                ('value', models.FloatField(default=0, verbose_name='Value')),
                ('unit', models.CharField(blank=True, default='', max_length=40, verbose_name='Unit')),
                ('labels', models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Labels')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recorded at')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observability_metrics', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Observability metric',
                'verbose_name_plural': 'Observability metrics',
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'category', '-recorded_at'], name='dms_observa_organiz_cab501_idx'), models.Index(fields=['name', '-recorded_at'], name='dms_observa_name_f47789_idx')],
            },
        ),
    ]
