# Generated by Django 6.0.1 on 2026-05-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0039_enterprise_observability_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает обработки'), ('RUNNING', 'В обработке'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка'), ('DEAD_LETTER', 'Dead letter'), ('REVIEWED', 'Проверено')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус'),
        ),
    ]
