# Generated by Django 6.0.1 on 2026-05-17 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0040_disaster_recovery_high_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrelation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_relations', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='documentrelation',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='documentrelation',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SYSTEM_SUGGESTION', 'System suggestion'), ('AI_SUGGESTION', 'AI suggestion'), ('IMPORTED', 'Imported')], db_index=True, default='MANUAL', max_length=30, verbose_name='Relation source'),
        ),
        migrations.AlterField(
            model_name='documentrelation',
            name='relation_type',
            field=models.CharField(choices=[('CONTRACT_TO_APPENDIX', 'Contract to appendix'), ('CONTRACT_TO_INVOICE', 'Contract to invoice'), ('CONTRACT_TO_ACT', 'Contract to act'), ('CONTRACT_TO_ADDITIONAL_AGREEMENT', 'Contract to additional agreement'), ('PARENT_CHILD', 'Parent child'), ('DUPLICATE', 'Duplicate'), ('REFERENCES', 'References'), ('SAME_COUNTERPARTY', 'Same counterparty'), ('SAME_PROJECT', 'Same project'), ('REPLACED_BY', 'Replaced by'), ('PRIMARY_DOCUMENT', 'Primary document'), ('ADDENDUM', 'Addendum'), ('ACT', 'Act'), ('INVOICE', 'Invoice'), ('SIGNED_SCAN', 'Signed scan'), ('REVISION', 'Revision'), ('OTHER', 'Other'), ('REPLACES', 'Заменяет'), ('APPENDIX_TO', 'Приложение к'), ('RELATED_TO', 'Связан с'), ('MENTIONS', 'Упоминает')], max_length=40, verbose_name='Тип связи'),
        ),
        migrations.AddIndex(
            model_name='documentrelation',
            index=models.Index(fields=['source', 'is_confirmed'], name='dms_documen_source_1f6e16_idx'),
        ),
    ]
