# Generated by Django 6.0.1 on 2026-05-17 22:29

import django.db.models.deletion
import dms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0041_advanced_document_relation_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('DOCUMENT_RELATION_CREATED', 'Document relation created'), ('DOCUMENT_RELATION_DELETED', 'Document relation deleted'), ('DOCUMENT_UPLOADED', 'Документ загружен'), ('DOCUMENT_UPDATED', 'Документ обновлен'), ('DOCUMENT_VIEWED', 'Документ просмотрен'), ('DOCUMENT_DOWNLOADED', 'Документ скачан'), ('DOCUMENT_VERSION_VIEWED', 'Версия документа просмотрена'), ('DOCUMENT_VERSION_DOWNLOADED', 'Версия документа скачана'), ('DOCUMENT_DELETED', 'Документ удален'), ('DOCUMENT_ACCESS_GRANTED', 'Доступ к документу выдан'), ('DOCUMENT_ACCESS_REVOKED', 'Доступ к документу отозван'), ('DOCUMENT_STATUS_CHANGED', 'Статус документа изменен'), ('AI_PROCESSING_STARTED', 'AI-обработка начата'), ('AI_PROCESSING_COMPLETED', 'AI-обработка завершена'), ('AI_PROCESSING_FAILED', 'AI-обработка завершилась ошибкой'), ('AI_FIELD_CONFIRMED', 'AI-поле подтверждено'), ('AI_FIELD_REJECTED', 'AI-поле отклонено'), ('AI_FIELDS_APPLIED', 'AI-поля применены к документу'), ('IMPORT_BATCH_CREATED', 'Партия импорта создана'), ('IMPORT_FILE_IMPORTED', 'Файл импортирован'), ('IMPORT_FILE_DUPLICATE', 'Дубликат при импорте'), ('IMPORT_FILE_FAILED', 'Ошибка импорта файла'), ('WORKFLOW_STARTED', 'Workflow started'), ('WORKFLOW_APPROVED', 'Workflow approved'), ('WORKFLOW_REJECTED', 'Workflow rejected'), ('WORKFLOW_CHANGES_REQUESTED', 'Workflow changes requested'), ('WORKFLOW_COMMENTED', 'Workflow commented'), ('WORKFLOW_COMPLETED', 'Workflow completed'), ('EXCHANGE_SENT', 'Document exchange sent'), ('EXCHANGE_OPENED', 'Document exchange opened'), ('EXCHANGE_DOWNLOADED', 'Document exchange downloaded'), ('EXCHANGE_ACCEPTED', 'Document exchange accepted'), ('EXCHANGE_REJECTED', 'Document exchange rejected'), ('EXCHANGE_COMMENTED', 'Document exchange commented'), ('EXCHANGE_RECEIVED', 'B2B document exchange received'), ('EXCHANGE_EXPIRED', 'Document exchange link expired'), ('EXCHANGE_REVOKED', 'Document exchange link revoked'), ('INTEGRATION_CONNECTION_CREATED', 'Integration connection created'), ('INTEGRATION_SYNC_JOB_CREATED', 'Integration sync job created'), ('EXTERNAL_REFERENCE_LINKED', 'External reference linked'), ('BILLING_SUBSCRIPTION_CREATED', 'Billing subscription created'), ('DOCUMENT_SEARCHED', 'Document search performed')], db_index=True, max_length=64, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('DOCUMENT', 'Documents'), ('VERSION', 'Document versions'), ('AUDIT', 'Audit events'), ('PROCESSING_RESULT', 'Processing results'), ('TEMPORARY_FILE', 'Temporary files')], db_index=True, max_length=40, verbose_name='Scope')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('retention_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Retention days')),
                ('action', models.CharField(choices=[('REVIEW_ONLY', 'Review only'), ('MANUAL_DELETE_AFTER_APPROVAL', 'Manual delete after approval'), ('LEGAL_HOLD', 'Legal hold')], default='REVIEW_ONLY', max_length=40, verbose_name='Action')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organization', models.ForeignKey(blank=True, help_text='Empty organization means global default policy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Retention policy',
                'verbose_name_plural': 'Retention policies',
                'ordering': ['organization__name', 'scope', 'name'],
                'indexes': [models.Index(fields=['organization', 'scope', 'is_active'], name='dms_retenti_organiz_a654a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'scope', 'name'), name='unique_retention_policy_name_per_scope')],
            },
        ),
        migrations.CreateModel(
            name='SensitiveEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('IIN', 'IIN'), ('BIN', 'BIN'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('AMOUNT', 'Amount'), ('PERSONAL_NAME', 'Personal name'), ('OTHER_PERSONAL_DATA', 'Other personal data')], db_index=True, max_length=40, verbose_name='Entity type')),
                ('raw_value_hash', models.CharField(db_index=True, max_length=64, verbose_name='Raw value hash')),
                ('masked_value', models.CharField(blank=True, default='', max_length=160, verbose_name='Masked value')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Confidence')),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='Source')),
                ('context', models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Safe context')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_entities', to='dms.document', verbose_name='Document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_entities', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Sensitive entity',
                'verbose_name_plural': 'Sensitive entities',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'entity_type', '-created_at'], name='dms_sensiti_organiz_f7cad9_idx'), models.Index(fields=['document', 'entity_type'], name='dms_sensiti_documen_711d66_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'document', 'entity_type', 'raw_value_hash', 'source'), name='unique_sensitive_entity_per_document_source')],
            },
        ),
    ]
