# Generated by Django 6.0.1 on 2026-05-18 08:32

import django.db.models.deletion
import dms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0042_enterprise_security_data_governance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planquota',
            name='usage_event_type',
            field=models.CharField(choices=[('document.relation_created', 'Document relation created'), ('document.relation_deleted', 'Document relation deleted'), ('document.uploaded', 'Document uploaded'), ('import.batch_created', 'Import batch created'), ('import.file_imported', 'Import file imported'), ('import.file_duplicate', 'Import file duplicate'), ('import.file_failed', 'Import file failed'), ('ai.processing_started', 'AI processing started'), ('ai.processing_completed', 'AI processing completed'), ('ai.processing_failed', 'AI processing failed'), ('workflow.started', 'Workflow started'), ('workflow.action', 'Workflow action'), ('exchange.event', 'Exchange event'), ('evidence.exported', 'Evidence exported'), ('integration.connection_created', 'Integration connection created'), ('integration.sync_job_created', 'Integration sync job created'), ('integration.external_reference_linked', 'External reference linked'), ('ai.document_processed', 'AI document processed'), ('ocr.page_processed', 'OCR page processed'), ('embedding.chunk_processed', 'Embedding chunk processed'), ('search.rerank_request', 'Search rerank request'), ('ai.cost_unit', 'AI cost unit')], db_index=True, max_length=80, verbose_name='Usage event type'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='event_type',
            field=models.CharField(choices=[('document.relation_created', 'Document relation created'), ('document.relation_deleted', 'Document relation deleted'), ('document.uploaded', 'Document uploaded'), ('import.batch_created', 'Import batch created'), ('import.file_imported', 'Import file imported'), ('import.file_duplicate', 'Import file duplicate'), ('import.file_failed', 'Import file failed'), ('ai.processing_started', 'AI processing started'), ('ai.processing_completed', 'AI processing completed'), ('ai.processing_failed', 'AI processing failed'), ('workflow.started', 'Workflow started'), ('workflow.action', 'Workflow action'), ('exchange.event', 'Exchange event'), ('evidence.exported', 'Evidence exported'), ('integration.connection_created', 'Integration connection created'), ('integration.sync_job_created', 'Integration sync job created'), ('integration.external_reference_linked', 'External reference linked'), ('ai.document_processed', 'AI document processed'), ('ocr.page_processed', 'OCR page processed'), ('embedding.chunk_processed', 'Embedding chunk processed'), ('search.rerank_request', 'Search rerank request'), ('ai.cost_unit', 'AI cost unit')], db_index=True, max_length=80, verbose_name='Event type'),
        ),
        migrations.CreateModel(
            name='ProcessingCostPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('code', models.SlugField(max_length=80, verbose_name='Code')),
                ('policy_type', models.CharField(choices=[('immediate', 'Immediate'), ('batch_30_min', 'Batch 30 min'), ('hourly', 'Hourly'), ('nightly', 'Nightly'), ('manual', 'Manual'), ('archive_only', 'Archive only'), ('priority', 'Priority')], db_index=True, max_length=30, verbose_name='Policy type')),
                ('max_cost_units', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Max cost units')),
                ('schedule_delay_minutes', models.PositiveIntegerField(default=0, verbose_name='Schedule delay minutes')),
                ('ocr_allowed', models.BooleanField(default=True, verbose_name='OCR allowed')),
                ('gpu_allowed', models.BooleanField(default=True, verbose_name='GPU allowed')),
                ('priority', models.PositiveSmallIntegerField(default=5, verbose_name='Queue priority')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organization', models.ForeignKey(blank=True, help_text='Empty organization means global reusable policy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_cost_policies', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Processing cost policy',
                'verbose_name_plural': 'Processing cost policies',
                'ordering': ['organization__name', 'max_cost_units', 'policy_type'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingCostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_count', models.PositiveIntegerField(default=1, verbose_name='Document count')),
                ('page_count', models.PositiveIntegerField(default=1, verbose_name='Page count')),
                ('ocr_needed', models.BooleanField(default=False, verbose_name='OCR needed')),
                ('chunks_count', models.PositiveIntegerField(default=0, verbose_name='Chunks count')),
                ('embedding_model', models.CharField(blank=True, default='', max_length=120, verbose_name='Embedding model')),
                ('processing_time_ms', models.PositiveIntegerField(default=0, verbose_name='Processing time ms')),
                ('estimated_cost_units', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estimated cost units')),
                ('recommended_policy', models.CharField(blank=True, default='', max_length=30, verbose_name='Recommended policy')),
                ('route_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Route reason')),
                ('quota_snapshot', models.JSONField(blank=True, default=dict, validators=[dms.models.validate_no_plaintext_secrets], verbose_name='Quota snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_cost_estimates', to='dms.document', verbose_name='Document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_cost_estimates', to='dms.organization', verbose_name='Organization')),
                ('processing_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_estimates', to='dms.processingjob', verbose_name='Processing job')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_estimates', to='dms.processingcostpolicy', verbose_name='Policy')),
            ],
            options={
                'verbose_name': 'Processing cost estimate',
                'verbose_name_plural': 'Processing cost estimates',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingCostQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_type', models.CharField(choices=[('ai_documents', 'AI documents/month'), ('ocr_pages', 'OCR pages/month'), ('embeddings', 'Embeddings/month'), ('rerank_requests', 'Rerank requests/month'), ('cost_units', 'AI cost units/month')], db_index=True, max_length=40, verbose_name='Quota type')),
                ('monthly_limit', models.PositiveIntegerField(default=0, verbose_name='Monthly limit')),
                ('warning_percent', models.PositiveSmallIntegerField(default=80, verbose_name='Warning percent')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Unlimited')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_cost_quotas', to='dms.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Processing cost quota',
                'verbose_name_plural': 'Processing cost quotas',
                'ordering': ['organization__name', 'quota_type'],
            },
        ),
        migrations.AddIndex(
            model_name='processingcostpolicy',
            index=models.Index(fields=['organization', 'policy_type', 'is_active'], name='dms_process_organiz_63d64d_idx'),
        ),
        migrations.AddIndex(
            model_name='processingcostpolicy',
            index=models.Index(fields=['is_default', 'is_active'], name='dms_process_is_defa_cc2470_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingcostpolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_processing_cost_policy_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='processingcostpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='unique_global_processing_cost_policy_code'),
        ),
        migrations.AddIndex(
            model_name='processingcostestimate',
            index=models.Index(fields=['organization', '-created_at'], name='dms_process_organiz_f0784c_idx'),
        ),
        migrations.AddIndex(
            model_name='processingcostestimate',
            index=models.Index(fields=['document', '-created_at'], name='dms_process_documen_c1eaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='processingcostestimate',
            index=models.Index(fields=['recommended_policy', '-created_at'], name='dms_process_recomme_b30886_idx'),
        ),
        migrations.AddIndex(
            model_name='processingcostquota',
            index=models.Index(fields=['organization', 'quota_type', 'is_active'], name='dms_process_organiz_619a76_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingcostquota',
            constraint=models.UniqueConstraint(fields=('organization', 'quota_type'), name='unique_processing_cost_quota_per_org'),
        ),
    ]
