apiVersion: v1
kind: Secret
metadata:
  name: dms-secrets
  namespace: dms
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "replace-with-kubernetes-secret-manager-value"
  POSTGRES_PASSWORD: "replace-with-kubernetes-secret-manager-value"
